name: photoreboot
description: Face Restoration Engine.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^6.0.3
  bloc: ^8.1.1
  dio: ^5.1.0
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  http_parser: ^4.0.2
  hydrated_bloc: ^9.1.0
  image_picker: ^0.8.7
  intl: ^0.17.0
  syncfusion_flutter_pdf: ^21.1.41

dev_dependencies:
  auto_route_generator: ^6.0.1
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
