name: photoreboot
description: Face Restoration Engine.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^6.4.0
  bloc: ^8.1.1
  dio: ^5.1.0
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hicons: ^0.0.1
  flutter_pdfview: ^1.3.0
  flutter_svg: ^2.0.5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  #http_parser: ^4.0.2
  hydrated_bloc: ^9.1.1
  image_picker: ^0.8.7
  intl: ^0.17.0
  json_annotation: ^4.8.0
  line_icons: ^2.0.1
  #material_color_utilities: ^0.2.0
  path_provider: ^2.0.14
  percent_indicator: ^4.2.3
  #qr: ^2.1.0
  #qr_flutter: ^4.0.0
  slang_flutter: ^3.16.0
  syncfusion_flutter_pdf: ^21.1.41
  uuid: ^3.0.7
  #uuidv6: ^1.0.0+1
  flutter_dotenv: ^5.0.2
  #pdf_render: ^1.3.8

dev_dependencies:
  auto_route_generator: ^6.2.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_gen: ^5.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  slang: ^3.16.2
  slang_build_runner: ^3.16.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/utils/
    - .env
flutter_assets:
  assets_path: assets/
  output_path: lib/src/generated/
  filename: assets.dart
